# This workflow will upload a Python Package to PyPI when a release is created
# using PyPI's Trusted Publishing feature.
# For more information see: https://docs.pypi.org/trusted-publishers/

name: Publish Python Package using Trusted Publishing

on:
  release:
    types: [published]

permissions:
  contents: read
  # IMPORTANT: this permission is mandatory for trusted publishing
  id-token: write

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/humanml # Optional: Link to the PyPI project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No username/password needed, uses OIDC token

